# Generated by Django 5.1.6 on 2025-02-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoregistration',
            old_name='official_email',
            new_name='email',
        ),
    ]
