# Generated by Django 5.1.1 on 2025-02-20 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoregistration',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ngoregistration',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ngoregistration',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='ngo_profiles/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NGOOTPVerification',
        ),
    ]
