# Generated by Django 5.1.6 on 2025-02-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ngoregistration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoregistration',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
