# Generated by Django 5.1.6 on 2025-02-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ngoregistration_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='ngoregistration',
            name='password',
            field=models.CharField(default='temporary_password', max_length=255),
            preserve_default=False,
        ),
    ]
