# Generated by Django 5.1.6 on 2025-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoregistration',
            name='government_issued_id',
            field=models.CharField(max_length=20),
        ),
    ]
