# Generated by Django 5.1.6 on 2025-02-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ngoregistration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoregistration',
            name='government_issued_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
