# Generated by Django 5.1.6 on 2025-02-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ngoregistration_government_issued_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoregistration',
            name='government_issued_id',
            field=models.TextField(),
        ),
    ]
