# Generated by Django 5.1.6 on 2025-02-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ngoregistration_government_issued_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundpost',
            name='ngo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
