# Generated by Django 5.1.6 on 2025-02-22 10:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_fundpost_ngo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyDonation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ngo')),
            ],
            options={
                'unique_together': {('ngo', 'date')},
            },
        ),
    ]
