# Generated by Django 5.1.6 on 2025-02-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_ngoregistration_government_issued_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngoregistration',
            old_name='official_email',
            new_name='email',
        ),
    ]
