# Generated by Django 5.1.6 on 2025-02-22 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20250222_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundpost',
            name='fund_request',
        ),
        migrations.AddField(
            model_name='fundpost',
            name='ngo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fundpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_fund_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundpost',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='collected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/fund_images/'),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='ngo',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_ngo': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_fund_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundpost',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
