# Generated by Django 5.1.6 on 2025-02-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_fundpost_fund_request_fundpost_ngo_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
