# Generated by Django 5.1.6 on 2025-02-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_fundpost_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundpost',
            old_name='image',
            new_name='image_url',
        ),
    ]
