# Generated by Django 5.1.6 on 2025-02-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_image_fundpost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='fundpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/fund_images/'),
        ),
    ]
