# Generated by Django 5.1.6 on 2025-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_fundpost_image_url_fundpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpost',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
