# Generated by Django 5.1.6 on 2025-02-25 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_fundpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fund_requests/'),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ngoregistration'),
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
